### ISSUE TITLE
SUPEE 7405: PDOException Unknown Column main_table.data

### ISSUE THREAD

**Issue by Urst** [avstudnitz/AvS_FastSimpleImport#309]
Hello,

I try to import many products. These products are stored in an array. If I try to run the Import-Script I get the following Exception.

```
exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.data' in 'field list'' in /html/shop/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /html/shop/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /html/shop/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /html/shop/lib/Zend/Db/Statement.php(320): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /html/shop/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#4 /html/shop/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#5 /html/shop/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#6 /html/shop/lib/Zend/Db/Adapter/Abstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#7 /html/shop/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#8 /html/shop/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#9 /html/shop/lib/Varien/Data/Collection/Db.php(572): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#10 /html/shop/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#11 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product/Type/Abstract.php(163): Varien_Data_Collection->getIterator()
#12 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product/Type/Abstract.php(116): Mage_ImportExport_Model_Import_Entity_Product_Type_Abstract->_initAttributes()
#13 /html/shop/app/code/core/Mage/Core/Model/Config.php(1354): Mage_ImportExport_Model_Import_Entity_Product_Type_Abstract->__construct(Array)
#14 /html/shop/app/Mage.php(462): Mage_Core_Model_Config->getModelInstance('fastsimpleimpor...', Array)
#15 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php(464): Mage::getModel('fastsimpleimpor...', Array)
#16 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php(303): Mage_ImportExport_Model_Import_Entity_Product->_initTypeModels()
#17 /html/shop/app/code/core/Mage/Core/Model/Config.php(1354): Mage_ImportExport_Model_Import_Entity_Product->__construct(Array)
#18 /html/shop/app/Mage.php(462): Mage_Core_Model_Config->getModelInstance('fastsimpleimpor...', Array)
#19 /html/shop/app/code/community/AvS/FastSimpleImport/Model/Import.php(80): Mage::getModel('fastsimpleimpor...')
#20 /html/shop/stufe9.php(20464): AvS_FastSimpleImport_Model_Import->processProductImport(Array)
#21 {main}

Next exception 'Zend_Db_Statement_Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'main_table.data' in 'field list'' in /html/shop/lib/Zend/Db/Statement/Pdo.php:234
Stack trace:
#0 /html/shop/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#1 /html/shop/lib/Zend/Db/Statement.php(320): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#2 /html/shop/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#3 /html/shop/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 /html/shop/lib/Varien/Db/Adapter/Pdo/Mysql.php(419): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 /html/shop/lib/Zend/Db/Adapter/Abstract.php(734): Varien_Db_Adapter_Pdo_Mysql->query('SELECT `main_ta...', Array)
#6 /html/shop/lib/Varien/Data/Collection/Db.php(740): Zend_Db_Adapter_Abstract->fetchAll('SELECT `main_ta...', Array)
#7 /html/shop/app/code/core/Mage/Core/Model/Resource/Db/Collection/Abstract.php(521): Varien_Data_Collection_Db->_fetchAll('SELECT `main_ta...', Array)
#8 /html/shop/lib/Varien/Data/Collection/Db.php(572): Mage_Core_Model_Resource_Db_Collection_Abstract->getData()
#9 /html/shop/lib/Varien/Data/Collection.php(741): Varien_Data_Collection_Db->load()
#10 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product/Type/Abstract.php(163): Varien_Data_Collection->getIterator()
#11 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product/Type/Abstract.php(116): Mage_ImportExport_Model_Import_Entity_Product_Type_Abstract->_initAttributes()
#12 /html/shop/app/code/core/Mage/Core/Model/Config.php(1354): Mage_ImportExport_Model_Import_Entity_Product_Type_Abstract->__construct(Array)
#13 /html/shop/app/Mage.php(462): Mage_Core_Model_Config->getModelInstance('fastsimpleimpor...', Array)
#14 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php(464): Mage::getModel('fastsimpleimpor...', Array)
#15 /html/shop/app/code/core/Mage/ImportExport/Model/Import/Entity/Product.php(303): Mage_ImportExport_Model_Import_Entity_Product->_initTypeModels()
#16 /html/shop/app/code/core/Mage/Core/Model/Config.php(1354): Mage_ImportExport_Model_Import_Entity_Product->__construct(Array)
#17 /html/shop/app/Mage.php(462): Mage_Core_Model_Config->getModelInstance('fastsimpleimpor...', Array)
#18 /html/shop/app/code/community/AvS/FastSimpleImport/Model/Import.php(80): Mage::getModel('fastsimpleimpor...')
#19 /html/shop/stufe9.php(20464): AvS_FastSimpleImport_Model_Import->processProductImport(Array)
#20 {main}PHP Fatal error:  Call to a member function setBehavior() on a non-object in /html/shop/app/code/community/AvS/FastSimpleImport/Model/Import.php on line 84
```

I use version 0.6.4. But I tried the new 0.7.0 Versiona too and the same Error occured. Looks like the Error came with the Security Patch SUPEE 7405. Before it was good. I use Magento 1.7.0.2.

Thank you very much for your Help!

**Comment by Urst** [comment]
Fixed the Issue. Problem was 	```
<cache>
		<backend>apc</backend>
		<prefix>MYSTORE_</prefix>
	</cache>
```

in my local.xml
